### ISSUE TITLE
Napájení - modul od Honzy Chrousta

### ISSUE THREAD

**Issue by Alsa-Tucnak** [ODZ-UJF-AV-CR/FIK-6#1]
Poslouží k napájení autopilota, LoRa modemů i iontometru. Bude potřeba ve 2 ks.

- [x] sehnat 2 funkční moduly od @ChroustJan  (možno použít součástky ze 3 nefunkčních z ODZ)

- [x] zkontrolovat baterky, případně sehnat nové

**Comment by ChroustJan** [comment]
@Alsa-Tucnak ví se co s moduly je? Pokud se na ně mám podívat, tak je bude potřeba pak doručit ke mě. Pak je na zvážení zda bude rentabilní oprava.

**Comment by kaklik** [comment]
Jeden z modulů se mi dnes zřejmě podařilo "opravit", tím že jsem v něm dobil akumulátory externím zdrojem na napětí při kterém začala fungovat nabíjecí elektronika modulu. Modul totiž má mnoho bezpečnostních ochran a podpětí před nabíjením patří mezi jednu z nich. 

Modul LION2CELL01C je teď v BASE na stole v tomhle stavu: 

![20201029_204300](https://user-images.githubusercontent.com/1194177/97631253-f53b7900-1a30-11eb-850a-341410cd8465.jpg)

Pro nabíjení stačí zapnout vypínač na napájení.  Po zmáčknutí tlačítka vedle LED lze přibližně zjistit, jak moc je modul nabitý. 
Opravu je potřeba ověřit používáním modulu, neboť lze očekávat že akumulátory nebudou po dlouhodebém podbití zrovna v dobrém stavu. Je tak zřejmě vhodné, aby s ním @Sommema4  zkusil napájet Iontometr #6. 

Druhý z modulů je zřejmě poškozen vážněji - nedobíjí se a místo pojistek má vletované drátky. Ten bude asi potřebovat nějaký odbornější zásah nejspíše u @ChroustJan. 

Jinak nebyla pravda, že v ODZ nefungoval žádný. Jeden ze zmíněných třech modulů je zřejmě trvale používán spolu s NB detektorem a ten je v BASE a podle všeho funguje.

**Comment by Alsa-Tucnak** [comment]
Výborná zpráva, že jeden funguje. Mohl by se toho tedy @Sommema4 ujmout, jestli se staví někdy na ODZ, a vyzkoušet ho s iontometrem?

Druhý nefungující modul tedy musíme dopravit @ChroustJan. Bude to stačit až v týdnu 9.-13.11.? Dříve se do Prahy nedostanu, abych to Honzovi převezla a nikoho jiného s tím teď uhánět nechci. Měl bys na to Honzo v tom týdnu případně čas?

Třetí modul je tedy sice používaný (díky za upřesnění @kaklik ), ale dal by se případně na balón půjčit @kakl ?

**Comment by ChroustJan** [comment]
Budu s tím předběžně počítat.

**Comment by kakl** [comment]
Ten treti modul ano, ale nevim, jestli i baterky. Casto se vybije a dlouho
lezel nenabity.

**Comment by Sommema4** [comment]
Dneska jsem zkoušel modul LION2CELL01C, co leží v base na stole. Multimetr mi ukazoval na výstupu asi 0,4 V a to samý na vstupu. Je možný, že je rozbitý ten bílý modul, do kterýho se strká adaptér @kaklik? Pokud je to bílý v pohodě, tak je asi něco špatně něco v tom modulu s akumulátorama. Když jsem se zkusil kouknout, jak moc jsou nabitý baterie, tak se mi rozsvítilo jenom to první světýlko.

**Comment by kaklik** [comment]
> Dneska jsem zkoušel modul LION2CELL01C, co leží v base na stole. Multimetr mi ukazoval na výstupu asi 0,4 V a to samý na vstupu. Je možný, že je rozbitý ten bílý modul, do kterýho se strká adaptér @kaklik? Pokud je to bílý v pohodě, tak je asi něco špatně něco v tom modulu s akumulátorama. Když jsem se zkusil kouknout, jak moc jsou nabitý baterie, tak se mi rozsvítilo jenom to první světýlko.

že se ti rozsvítilo první světýlko je v pořádku, ten modul jsem nenechával nabíjet a když jsem odcházel, tak byl nabitej tak na první tři ledky. 

Vůbec netuším co jsi měřil, když si naměřil 0.4 V a zároveň se ti rozsvítila led u modulu..  Aby byl rozbitý modul do kterýho se strká adaptér je prakticky nemožné.

Co to udělalo po tom, co jsi zapnul vypínač tak jak to leželo na stole?

**Comment by kaklik** [comment]
Dneska jsem jedinný nefunkční modul LION2CELL01C odvezl @ChroustJan  a  @Sommema4 jsem viděl dnes druhý modul LION2CELL01C testovat na ODZ.

**Comment by ChroustJan** [comment]
Modul jsem opravil. Byl předán @kaklik

**Comment by kaklik** [comment]
Balon dovedl fungovat na současné akumulátory několik hodin.

**Comment by kaklik** [comment]
Balon s jedním z opravených modulů letěl a vydržel fungovat po celou dobu letu.  Po přistání na něm po zmáčknutí tlačítka svítila jedna LED.
