### ISSUE TITLE
Sférická kamera

### ISSUE THREAD

**Issue by roman-dvorak** [ODZ-UJF-AV-CR/FIK-6#12]
Použitá kamera je [Ricoh Theta V](https://theta360.com/en/about/theta/v.html).

Existují nějaké návody, které využívají externí paměť/flashku. Problém je, že nikde neřeši napájení a tyto "redukce" zmenšují spolehlivost řešení.  https://theta360developers.github.io/usbstorageplugin/

Je tedy asi potřeba zvolit jeden z těchto postupů a otestovat ho.

**Comment by kaklik** [comment]
Ke kameře byla letos připojena powerbanka podobným způsobem jako loni.  Zatím není známo zda na ní jsou nějaké obrázky, protože po stržení ze stromu nejde zapnout.

**Comment by kaklik** [comment]
@kakl  úspěšně stáhnul snímky z kamery. Kamera se vypla ještě před přistáním, pravděpodobně v důsledku zamrznutí nebo odpojení powerbanky.
