### ISSUE TITLE
Montáž TFGPS01

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/FIK-6#14]
@ChroustJan  připravil [TFGPS01](https://github.com/ThunderFly-aerospace/TFGPS01)

Nyní je potřeba celý GPS modul namontovat z vnitřní strany víka krabice #5. 

**Při manipulaci je nutné se vyhnout kontaktu ruky s keramickou částí antény a napařenými stříbrnými elektrodami. Může tím dojít k požkození antény**.

**Comment by Alsa-Tucnak** [comment]
Stačilo by případně vzít si rukavice? Je nějaký správný postup, jak ten modul připevnit? Předpokládám, že izolepa asi nebude úplně nejlepší nápad. @kaklik

**Comment by kaklik** [comment]
GPS modul byl do balonu namontován ve vytištěné krabičce od @roman-dvorak. Uchycení bylo realizováno přilepením na dual-lock suchého zipu na dno resp. vrch polystyrénové krabice gondoly balonu.
