### ISSUE TITLE
Zkontrolovat parametry autopilota

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/FIK-6#16]
- SDLOG_PROFILE - nastavit na logování od zapnutí po vypnutí
 - GPS nastavit na airborne

**Comment by roman-dvorak** [comment]
co se týče logování, tak je potřeba také zkontrolovat nastavení co vše se loguje. Protože autopilot umí logovat opravdu hodně dat, a nevím, jestli by se to v maximálnim režimu vešlo na kartu. 

Dále, jestli by se u letového kusu neměla udělat teplotní kalibrace senzorů.

**Comment by kaklik** [comment]
Tak SDkarta, která tam momentálně je má 16GB, ale nemám žádnou zkušenost s tím, zda logování funguje tak, že vytváří tak velký soubor v kuse, nebo se začnou logy dělit na menší. 

Teplotní kalibrace senzorů je dobrý nápad, ale úplně nevím jak to realizovat. Chtělo by to asi udělat někdy, kdy bude venku mrznout.

**Comment by roman-dvorak** [comment]
> Tak SDkarta, která tam momentálně je má 16GB, ale nemám žádnou zkušenost s tím, zda logování funguje tak, že vytváří tak velký soubor v kuse, nebo se začnou logy dělit na menší.

Nevím o tom, že by se logování dělilo nejdelší log, co jsem měl je 1.5GB v kuse. To byl tak cca hodinový (max 1.5h) log s největším logováním a logováním GPS. Dělení neproběhlo. 

Dělení myslíš kvůli omezení FS? 

A SD karta tam zůstane ta originální z CUAV? Myslel jsem, že se tam kupovaly zvláštní micro-sd karty, které ale byly jen 8GB (???)

**Comment by kaklik** [comment]
> Dělení myslíš kvůli omezení FS?
>

Spíše kvůli riziku poškození souboru a předpokládám, že je snazší obnovovat menší soubor, než jeden obrovský. 
 
> A SD karta tam zůstane ta originální z CUAV? Myslel jsem, že se tam kupovaly zvláštní micro-sd karty, které ale byly jen 8GB 

Tohle je otázka na @Alsa-Tucnak  viz issue #11 
On ten balonový let je ale poměrně krátký tak 3hodiny maximálně. Zbytek dat je pak na zemi.

**Comment by kaklik** [comment]
Nastavené parametry autopilota byly poznamenány do [nově vytvořeného airframe balonu](https://github.com/ThunderFly-aerospace/PX4Firmware/blob/tf/add_tf-b1/ROMFS/px4fmu_common/init.d/airframes/18001_TF-B1).  Skutečně použité parametry jsou zároveň poznamenány v letovém logu.
