### ISSUE TITLE
LoRa modem - s vlastní GPS a Arduinem

### ISSUE THREAD

**Issue by Alsa-Tucnak** [ODZ-UJF-AV-CR/FIK-6#2]
Slouží ke zjištění polohy balonu skrze komunikaci s pozemními radiovými stanicemi.

- [x] Zjistit kolik stojí LoRa modemy s Arduinem (@povik)

- [x] Koupit 2 tyto sestavy (@Alsa-Tucnak ), pokud bude stačit rozpočet (Iva), jinak půjčit (@kaklik )

- [x] Zprovoznit sestavu LoRa transceiver - Arduino - GPS, alespoň v jednom exempláři.

**Comment by kaklik** [comment]
Tak bych řekl, že na rozdíl od loňského roku, jsou nyní dostupné Arduino knihovny pro čip [SX1262](https://www.semtech.com/products/wireless-rf/lora-transceivers/sx1262), který máme v modulu [ISM02A](https://www.mlab.cz/module/ISM02A).

Těch knihoven zřejmě bohužel vzniklo několik nezávisle na sobě: 

- [tinytronix/SX126x](https://github.com/tinytronix/SX126x) - není vyzkoušeno s  LoRaWAN library
- [beegee-tokyo/SX126x-Arduino](https://github.com/beegee-tokyo/SX126x-Arduino) - obsahuje podporu  LoRaWAN
- [RadioLib SX1262](https://jgromes.github.io/RadioLib/class_s_x1262.html) - tohle je rozšíření jiné rozsáhlejí knihovny, o které nevím jestli jsme ji náhodou nepoužívali.
- [simple_sx1262](https://github.com/ngraziano/LMICPP-Arduino/tree/master/examples/simple_sx1262) - tohle vypadá na nějaký zřejmě funkční, ale neprodukční pokus [zdroj](https://www.thethingsnetwork.org/forum/t/sx1262-applications/28685/8) - určitě nebude implementována  LoRaWAN library
- [LoRaMac-node](https://github.com/Lora-net/LoRaMac-node/tree/master/src/radio/sx126x)  - LoRaWAN refereční projekt.

**Comment by povik** [comment]
Našel jsem [LacunaSpace/basicmac](https://github.com/LacunaSpace/basicmac), která má podporu pro SX1262. Na tuhle knihovnu se odkazuje autor [arduino-lmic](https://github.com/matthijskooijman/arduino-lmic), se kterou jsme měli úspěch minulý rok. Proto navrhuji pokračovat pokusem o zprovoznění té basicmac s ISM02A.

**Comment by povik** [comment]
Jinak s [LoRaMac-node](https://github.com/Lora-net/LoRaMac-node) jsem se seznámil při portování na PX4, a rád bych se s touto knihovnou už nesetkal. Knihovny vycházející z [lmic](https://github.com/mcci-catena/ibm-lmic), což je to arduino-lmic i basicmac, jsou mi bližší.

**Comment by kaklik** [comment]
Vzhledem k tomu, že @povik úspěšně rozfungoval modul [ISM02A](https://github.com/mlab-modules/ISM02) připojený a autopilotovi #10. 
Tak můžeme stejný modul použít k připojení k Arduinu běžícím na ATMEGA1284P-AU, které se používá v [dataloggerech AIRDOSU](https://github.com/mlab-modules/DATALOGGER01). Díky tomu jsou v BASE pravděpodobně volné testovací moduly s tímto MCU, které lze použít k sestavení vysílače pro balon. @kaklik  je zkusí najít.

**Comment by kaklik** [comment]
@povik  Jsem dneska dovezl modul [ATmegaTQ4401A](https://github.com/MLAB-project/Modules/tree/master/MCU_CPU/AVR/ATmegaTQ4401A) z prototypu AIRDOS dataloggeru osazený ATMEGA1284P. 
Bohužel jsem zapomněl na [GPS01B](https://github.com/MLAB-project/Modules/tree/master/sensors/GPS01B), který je potřebný pro zprovoznění kompletní sestavy. Neboť Arduino musí GPS modul i správně znicializovat, aby měřil i ve výškách nad 12km.  GPS01B modul je potřeba ještě povikovi dodat. Zřejmě půjde použít nějaký zbylý z airdosů.

**Comment by Alsa-Tucnak** [comment]
To tedy znamená, že vše potřebné už někde máme? Nebo mám zkoušet dokoupit ještě něco dalšího? Kolik kusů ISM02A s tím správným čipem a modulů ATmegaTQ4401A máme tedy k dispozici (@kaklik)? A nebude vadit, když se půjčí tyhle věci z AIRDOSů (@kakl)?

**Comment by povik** [comment]
Ano. K lora vysílání máme všechno — dva kusy ISM02A, jednoho autopilota a jeden modul s vhodnou atmega. Z toho postavíme dva nezávislé vysílače, jak jsme se dohodli na poslední schůzce. Mám to u sebe teď já.

**Comment by kaklik** [comment]
@povik Povik sestavil, oživil a otestoval sestavu Arduino ISM02A, která vysílá packety obsahující souřadnice do TTN.
