### ISSUE TITLE
Zprovoznit upload dat do hubhab 

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/FIK-6#21]
Na kapybaře je potřeba zprovoznit uploader dat z [TTN](https://www.thethingsnetwork.org/) na https://tracker.habhub.org/. 

Skript, který se k tomu používal loni je tenhle: https://github.com/ODZ-UJF-AV-CR/FIK-6/tree/FIK-6/sw/Telemetry_receiver

Začít je potřeba registrací člověka, který to zajistí do TTN.

**Comment by roman-dvorak** [comment]
Je v něm potřeba nastavit tyto dva parametry a zmenit callsign na začátku
https://github.com/ODZ-UJF-AV-CR/FIK-6/blob/FIK-6/sw/Telemetry_receiver/habitat_uploader.py#L112-L113

**Comment by kaklik** [comment]
A ještě se to pravděpodobně musí na kapybaře spustit ve dvou instancích.. Protože máme primary a secondary LoRa vysílač.

**Comment by kaklik** [comment]
Upload dat z TTN přes kapybaru nakonec zprovoznil @povik dokončením úprav existujícího kódu pro python 3.  V době letu uploader běžel na kapybaře.
