### ISSUE TITLE
Ověřit logované hodnoty 

### ISSUE THREAD

**Issue by roman-dvorak** [ODZ-UJF-AV-CR/FIK-6#23]
Tento test je potřeba udělat jako jeden z posledních (resp. s letovou verzí FW). 

Ze zaznamenaného logu zjistit, jestli obsahuje:

 - [x] GPS dump
 - [x] Existence pozice
 - [x] Jestli se loguje orientace v prostoru

**Comment by kaklik** [comment]
GPS dump jsem v parametrech záměrně nezapínal, aby nebyla zbytečně zvětšena velikost logu viz #19. 

Další body je poměrně těžké ověřit, protože log není kde si pořádně prohlédnout. Díky velikosti souboru nelze použít veřejné https://review.px4.io/ které má omezení na velikost uploadovaného souboru. 

Vzhledem k tomu, že na ODZ budou teď asi probíhat experimenty s UAV častěji, tak by možná bylo dobré zprovoznit [flight_review](https://github.com/ThunderFly-aerospace/flight_review) na [kapybaře](https://kapybara.ujf.cas.cz/) a log prohlédnout tam @povik ?. 

Zároveň by by tam mohly být i data z loňského letu, který má s prohlížením souborů podobný problém.

**Comment by povik** [comment]
> Vzhledem k tomu, že na ODZ budou teď asi probíhat experimenty s UAV častěji, tak by možná bylo dobré zprovoznit [flight_review](https://github.com/ThunderFly-aerospace/flight_review) na [kapybaře](https://kapybara.ujf.cas.cz/) a log prohlédnout tam @povik ?.

Podívám se na to. Neměl by to být problém.

**Comment by kaklik** [comment]
Na kapybaře nové fligh_review běží a zobrazuje log z letu balonu.
