### ISSUE TITLE
Úklid v repozitářích a záloha letových dat

### ISSUE THREAD

**Issue by kaklik** [ODZ-UJF-AV-CR/FIK-6#24]
Nyní je potřeba commitnout všechny reálně použité kódy a uložit naměřená data na kapybaru. 

- [x] commit upraveného hubhab LoRa uploaderu z kapybary na které běžel. ( @povik  nebo @Sommema4 )
- [x] záloha logovaných souborů z auta a videozáznamu @kaklik 
- [x] Release binárních souborů FIK-6

**Comment by povik** [comment]
https://github.com/ODZ-UJF-AV-CR/FIK-6/commit/7871525418e77cd88b7ba9765dc4eafc937ca30e

**Comment by kaklik** [comment]
Není náhodou možné, že by z toho LoRa transportu existoval i nějaký log? Bylo by totiž fajn, vědět, jak to bylo s intenzitou signálu z LoRa secondary v celém průběhu.  Můj předpoklad totiž je, že ten signál byl asi slabý v důsledku nějakého poškození připojení antény.. A je možné že to v nějaké formě existovalo už před kritickým složením gondoly před startem.

**Comment by kaklik** [comment]
Tak jsem ještě přesunul tyhle logy 

![image](https://user-images.githubusercontent.com/1194177/104438527-639fca00-5590-11eb-8355-d621aec024ca.png)

do `/storage/experiments/2020/12_fik6/Flight`  

v klonu repozitáře /home/sommema4/git/FIK-6/sw/Telemetry_receiver jsem nenašel žádné nepushnuté změny. 

Tím je úklid po letu dokončen.  :)
