### ISSUE TITLE
Připojení měřicích zařízení k palubnímu počítači FMUv5

### ISSUE THREAD

**Issue by roman-dvorak** [ODZ-UJF-AV-CR/FIK-6#3]
Autopilot umožňuje logovat data z nějakých měřících zařízení umístěných na palubě balonu. K tomu, aby data byla přijmuta autopilotem musí mít správnou formu. A to musí se po sériovce posílat [MAVLink v2](https://mavlink.io/en/) pakety. Logovány budou pakety [Tunnel (#385)](https://mavlink.io/en/messages/common.html#TUNNEL).

Lze k tomu využít tato knihovna, která je automaticky generována z konfiguračních souborů: [c_library_v2](https://github.com/mavlink/c_library_v2)

Příklad komunikace payloadu založeném na arduinu s autopilotem je zde:
[TFUNIPAYLOAD.ino](https://github.com/ThunderFly-aerospace/TFUNIPAYLOAD/blob/master/SW/arduino/src/TFUNIPAYLOAD/TFUNIPAYLOAD.ino)

[Funkce na odeslání tunnel paketu](https://github.com/ThunderFly-aerospace/TFUNIPAYLOAD/blob/79eee22fe32725179d1df2b6ca72e901e2be1834/SW/arduino/src/TFUNIPAYLOAD/TFUNIPAYLOAD.ino#L50)

```  mav.SendTunnelData(data, sizeof(data), 0, 1, 0); ```
Tato funkce umožňuje poslat tunnel data do autopilota. Její argumenty jsou:
 * data ve formátu uint8_t [127]
 * délka dat
 * Typ dat (každý payload nebo typ logovaných dat bude mít své ID - na tom se domluvíme spolu - slouží pro snadné odlišení dat
 * Cílové sysid
 * Cílové compid

Pokud budeme chtít data logvat, tak cílové sysid a compid musí být 1, 1 (id autopilota) 

Autopilot má omezené množství paměti. Proto je důležité zajistit na straně payloadu, že nedojde k její zaplňení. Na konkrétních pravidlech se domluvíme podle toho, jak odesílaná data budou vypadat.

**Comment by kaklik** [comment]
Dobrá práce! Tohle bych řekl že je zřejmě hlavně pro Marka?  @Sommema4

**Comment by Sommema4** [comment]
Jo, tohle je super. Zkusím to během tohoto týdne implementovat na iontometr. Jediný problém je, že ten link na arduino příklad se mi nechce otevřít. Hází to 404.

**Comment by kaklik** [comment]
@Sommema4   Iontometr bude potřeba připojit na autopilotovi k [tomuto konektoru](https://github.com/pixhawk/Pixhawk-Standards/blob/master/DS-009%20Pixhawk%20Connector%20Standard.pdf) (signály nemusí být připojeny všechny): 

![image](https://user-images.githubusercontent.com/1194177/98296308-06e1cb00-1fb3-11eb-895c-297fa4297aa6.png)

Důležité jsou zde zejména ty napěťové úrovně signálů, které je potřeba dodržet (3.3V).  Pokud to tak na Iontometru není, tak je potřeba počítat s nějakým signálovým translátorem. 

Konektor, který tam pasuje máme a bude končit volnými drátky na které bude potřeba přiletovat výstup z Iontometru.

**Comment by kaklik** [comment]
Iontometr nakonec k palubnímu počítači připojen nebyl. Zaznamenával data samostatně na svojí SDkartu vzhledem k vlastním RTC hodinám.
