### ISSUE TITLE
Polystyrenová krabice

### ISSUE THREAD

**Issue by Alsa-Tucnak** [ODZ-UJF-AV-CR/FIK-6#5]
Vytvořit nebo sehnat box, ve kterém poletí přístroje.

- rozměry 26x26x26 cm

- tloušťka stěn minimálně 1,5 cm

- přihrádka na iontometr - s otvory na nasávání vzduchu

- vnější povrch červený - olepit červenou izolepou kvůli zpevnění?

**Comment by kaklik** [comment]
Gondola byla otestována reálným letem, který relativně vydržela i v četně přistání.  Pevnost gondoly je ale spíše na spodní hranici. 

Při přistání došlo plánovaně k destrukci antén, které tak absorbovaly část dopadové energie. 

![image](https://user-images.githubusercontent.com/1194177/102709945-1e4ced00-42af-11eb-875b-b2fd9db74aca.png)

Příště by asi bylo vhodné antény tisknout z materiálu který má větší impact strength, například PolyMax, aby došlo k ještě větší absorbci energie.

**Comment by roman-dvorak** [comment]
Unvitř gondoly byla po přistání proražená příčka iontometru. Iontometr byl z části v hlavním prostoru gondoly. K tomu mohlo snadno dojít i díky tomu, že nad  (resp. pod) přepážkou bylo dost volného prostoru, který byl jen trochu vyplněn rukavicemi. 

![20201219_163220_HDR](https://user-images.githubusercontent.com/5196729/102710375-15a9e600-42b2-11eb-9b63-ce025eb05f2e.jpg)
_Na fotce je iontometr ve stavu, v jakým byl v krabici nalezený. Polystyrenové víčko bylo trochu nadzvednuté kvůli vyfocení. Iontometr byl docela hmotný a navíc umístěn v horní části krabice._

Polystyrenová krabice byla ještě důkladně obalena potravinářskou fólií ve všech směrech. Pod anténami byla fólie umístěna pod polystyrenovým víkem s anténamy, tak aby nepřekážela anténám. Následně to celé bylo obtočeno lepící páskou.

>  Příště by asi bylo vhodné antény tisknout z materiálu který má větší impact strength, například PolyMax, aby došlo k ještě větší absorbci energie.

Na další roky byl prý pořízen průšament. Prý z důvodu, že se to tiskne na průšovo tiskárně.
