### ISSUE TITLE
Iontometr

### ISSUE THREAD

**Issue by Alsa-Tucnak** [ODZ-UJF-AV-CR/FIK-6#6]
- [x] Vyřešit napájení

- [x] Vytvořit 3D model pro uchycení trubic, vytisknout ho a odzkoušet 

- [x] Vymyslet umístění v polystyrenovém boxu (#5)

- [ ] Vyřešit ukládání dat z iontometru (#3)

Aktuální návrh umístění od @Sommema4  : 

![IMG_20201022_181859](https://user-images.githubusercontent.com/1194177/97496328-15076a00-1969-11eb-9576-4af70bb70f65.jpg)

**Comment by kaklik** [comment]
Odlehčení toho Iontometru je určitě fajn postup! :)  Mohlo by to pak umožnit i jeho budoucí využití na UAV, čemuž u těch komerčních, těžkých moc nevířím.. 
Nechcete si na Iontometr tady udělat samostatný repozitář?

**Comment by Sommema4** [comment]
Jo, napájení vyzkouším zítra v base a ukládání dat na autopilota se mi snad podaří dodělat do konce týdne. S uložením a 3D tiskem počítám s pomocí od @Alsa-Tucnak.

**Comment by Sommema4** [comment]
Napájení vyzkoušeno. Funguje to krásně. Bylo to dneska venku asi 5-6 hodin (cca. 5°C). Vybilo se to z 6 světýlek (8,3 V) na 1 světýlko (7,2 V). Potom už jsem musel jít, takže jsem to vypnul. Podle datasheetu by mělo jít Arduino nano napájet i při 7 V, takže je tam asi i nějaká rezerva.

**Comment by kaklik** [comment]
> Napájení vyzkoušeno. Funguje to krásně. Bylo to dneska venku asi 5-6 hodin (cca. 5°C). Vybilo se to z 6 světýlek (8,3 V) na 1 světýlko (7,2 V). Potom už jsem musel jít, takže jsem to vypnul. Podle datasheetu by mělo jít Arduino nano napájet i při 7 V, takže je tam asi i nějaká rezerva.

Supr :)  
Teď ještě reálně mezi tím LION2CELL01C a Iontometrem bude tohle: 

![image](https://user-images.githubusercontent.com/1194177/98823848-e1314780-2432-11eb-846e-a153438c412d.png)

Tahle věc jednak řeší odbočku pro napájení autopilota a potom zároveň umožňuje měřit proud a napětí akumulátorů. 
Inotometr tak bude potřebo vybavit napájecím konektorem XT-60M, který dnes přeze @kakl  do BASY. 
Na napájecím modulu LION2CELL01C pak bude analogicky konektor XT-60F zapojený drátky do svorkovnice pro výstup napájecího napětí.    Zminěný měřící a napájecí modul se pak zapojí mezi tyto dva konektory.

**Comment by Sommema4** [comment]
Ok. Já myslel, že ten modul LION2CELL01C je dělaný tak, aby šlo měřit odběr a napětí přímo z něho. Umí tahle věc odstavit iontometr od napájení v případě nějakýho zkratu v iontometru?

**Comment by roman-dvorak** [comment]
Ne, neumí. Ta je naopak dělaná na to, aby uměla přenést velké proudy.

**Comment by kaklik** [comment]
> Ok. Já myslel, že ten modul LION2CELL01C je dělaný tak, aby šlo měřit odběr a napětí přímo z něho. Umí tahle věc odstavit iontometr od napájení v případě nějakýho zkratu v iontometru?

To je sice pravda, ale nemáme čas tohle implementovat. Takže jednodušší a rychlejší řešení teď je tam přidat tenhle modul.   Je to prostor ke zlepšení pro příště. ;)

Ono nějak hrozí riziko zkratu v iontometru?

**Comment by Sommema4** [comment]
Ok. Riziko snad není.
Viděl jsem, že v base jsou ty XT konektory. Doufal jsem, že to bude na nějakých kabelech. Já jsem tyhle konektory nikdy nepřidělával a nevím, jak se to dělá.

**Comment by kakl** [comment]
Pokud do iontometru tece malej proud, tak se pred nej muze dat napajeci
modul s vratnou pojistkou.

**Comment by kaklik** [comment]
> Ok. Riziko snad není.
> Viděl jsem, že v base jsou ty XT konektory. Doufal jsem, že to bude na nějakých kabelech. Já jsem tyhle konektory nikdy nepřidělával a nevím, jak se to dělá.

https://youtu.be/w0pMjZ-rFQA?t=115

**Comment by Sommema4** [comment]
Ještě se to bude muset trochu upravit, ale váha je výrazně nižší než byla předtím. Mohli bysme se vejít do 300 g.

![IMG_20201126_112444](https://user-images.githubusercontent.com/25387126/100339486-385e1d00-2fda-11eb-9896-e40df5a1ce48.jpg)

**Comment by kaklik** [comment]
Iontometr nakonec letěl jen s vlastnní SDkartou na kterou úspěšně uložil měřená data z celého letu. Viz následující graf od @Sommema4 : 

![132013339_306102537390100_9167043729814044555_n](https://user-images.githubusercontent.com/1194177/102714751-0b4b1480-42d1-11eb-81f1-61ab64fb8b37.png)
