### ISSUE TITLE
Naplnění balónu

### ISSUE THREAD

**Issue by Alsa-Tucnak** [ODZ-UJF-AV-CR/FIK-6#7]
- [x] Koupit helium

- [x] Sehnat průtokoměr

- [x] Pronajmout hangár v Příbrami

- [x] Vymyslet bezpečné nafouknutí, aby se nepoškodil povrch balónu

**Comment by Alsa-Tucnak** [comment]
Průtokoměr máme půjčený i se školením od paní Tomáškové, je u studentů na ODZ. Potřebujeme k němu sehnat klíč 30 a sikovky. Nemáte to někdo doma @kakl @kaklik ? Po přepravu velké lahve by se správně mělo sehnat povolení a hlavně vhodné auto, ve kterém půjde zabezpečit, že lahev při nehodě nezabije posádku. Můžeme sehnat nějakou dodávku, nebo myslíte, že bude stačit jedno z pracovních aut? Mohl by s tímto pomoct @onpl ?

Lahev se pak musí naložit už v pátek (nebo v běžné pracovní hodiny), protože jediné klíče od skladu lahví jsou na vrátnici.

**Comment by kaklik** [comment]
V balonu bylo letos použito podle záznamu z nafukování 6.35 m³ helia.
